base/urls.py
from django.urls import path, re_path
from .views import HomeView, Error403View
from .ajax import ComboUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'base'

## urls de la aplicación base
urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('error-403/', Error403View.as_view(), name = "error_403"),
]

urlpatterns += [
    re_path(r'^ajax/actualizar-combo/?$', login_required(ComboUpdateView.as_view()), name='combo_update'),
]

user/urls.py
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from .views import (
    NationalLevelUpdateView, StateLevelListView, StateLevelCreateView, StateLevelUpdateView, MunicipalLevelListView,
    MunicipalLevelCreateView, ParishLevelListView, ParishLevelCreateView, MunicipalLevelUpdateView, ParishLevelUpdateView,
    CommunalCouncilLevelListView, CommunalCouncilLevelCreateView, CommunalCouncilLevelUpdateView
)
from django.urls import reverse_lazy

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('reset/password_reset/', views.PasswordResetView.as_view(template_name='user/password_reset_form.html',
        email_template_name='user/password_reset_email.html',success_url=reverse_lazy('user:password_reset_done')),
        name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/',views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),

    path('cambiar-clave/', login_required(views.PasswordChangeView.as_view(template_name='user/password_change_form.html')),
        name='password_change'),
    path('cambiar-clave-hecho/', login_required(views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html')),
        name='password_change_done'),

    path('nacional/actualizar/<int:pk>/', login_required(NationalLevelUpdateView.as_view()), name='national_level_update'),
    path('estadal/', login_required(StateLevelListView.as_view()), name='state_level_list'),
    path('estadal/registrar/', login_required(StateLevelCreateView.as_view()), name='state_level_create'),

    path('estadal/actualizar/<int:pk>/', login_required(StateLevelUpdateView.as_view()), name='state_level_update'),
    path('municipal/', login_required(MunicipalLevelListView.as_view()), name='municipal_level_list'),
    path('municipal/registrar/', login_required(MunicipalLevelCreateView.as_view()), name='municipal_level_create'),

    path('municipal/actualizar/<int:pk>/', login_required(MunicipalLevelUpdateView.as_view()), name='municipal_level_update'),
    path('parroquial/', login_required(ParishLevelListView.as_view()), name='parish_level_list'),
    path('parroquial/registrar/', login_required(ParishLevelCreateView.as_view()), name='parish_level_create'),

    path('parroquial/actualizar/<int:pk>/', login_required(ParishLevelUpdateView.as_view()), name='parish_level_update'),
    path('comunal/', login_required(CommunalCouncilLevelListView.as_view()), name='communal_council_level_list'),
    path('comunal/registrar/', login_required(CommunalCouncilLevelCreateView.as_view()), name='communal_council_level_create'),

    path('comunal/actualizar/<int:pk>/', login_required(CommunalCouncilLevelUpdateView.as_view()), name='communal_council_level_update'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from base.models import Country, State, Municipality, Parish, CommunalCouncil
from django.utils.translation import ugettext_lazy as _
from base.constant import LEVEL, NATIONALITY

class Profile(models.Model):

    phone = models.CharField(
        max_length=15, verbose_name='Teléfono'
    )

    level = models.IntegerField(choices=LEVEL, verbose_name='Nivel')

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name='Usuario'
    )

    def __str__(self):
        return '%s | %s %s' % (self.user.username, self.user.first_name, self.user.last_name)

    class Meta:
        verbose_name = _('Perfil')
        verbose_name_plural = _('Perfiles')

class NationalLevel(models.Model):

    country = models.OneToOneField(
        Country, on_delete=models.CASCADE, verbose_name='País'
    )

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, verbose_name='Perfil'
    )

    def __str__(self):
        return '%s | %s %s | %s' % (self.profile.user.username, self.profile.user.first_name,
            self.profile.user.last_name, str(self.country))

    class Meta:
        verbose_name = _('Nivel Nacional')
        verbose_name_plural = _('Nivel Nacionales')

class StateLevel(models.Model):

    state = models.OneToOneField(
        State, on_delete=models.CASCADE, verbose_name='Estado'
    )

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, verbose_name='Perfil'
    )

    def __str__(self):
        return '%s | %s %s | %s' % (self.profile.user.username, self.profile.user.first_name,
        self.profile.user.last_name, str(self.state))

    class Meta:
        verbose_name = _('Nivel Estadal')
        verbose_name_plural = _('Nivel Estadales')

class MunicipalLevel(models.Model):

    municipality = models.OneToOneField(
        Municipality, on_delete=models.CASCADE, verbose_name='Municipio'
    )

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, verbose_name='Perfil'
    )

    def __str__(self):
        return '%s | %s %s | %s' % (self.profile.user.username, self.profile.user.first_name,
        self.profile.user.last_name, str(self.municipality))

    class Meta:
        verbose_name = _('Nivel Municipal')
        verbose_name_plural = _('Nivel Municipales')

class ParishLevel(models.Model):

    parish = models.ForeignKey(
        Parish, on_delete=models.CASCADE, verbose_name='Parroquia'
    )

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, verbose_name='Perfil'
    )

    def __str__(self):
        return '%s | %s %s | %s' % (self.profile.user.username, self.profile.user.first_name,
        self.profile.user.last_name, str(self.parish))

    class Meta:
        verbose_name = _('Nivel Parroquial')
        verbose_name_plural = _('Nivel Parroquiales')

class CommunalCouncilLevel(models.Model):

    communal_council = models.OneToOneField(
        CommunalCouncil, on_delete=models.CASCADE, verbose_name='Consejo Comunal'
    )

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, verbose_name='Perfil'
    )

    def __str__(self):
        return '%s | %s %s | %s' % (self.profile.user.username, self.profile.user.first_name,
        self.profile.user.last_name, str(self.communal_council))

    class Meta:
        verbose_name = _('Nivel Consejo Comunal')
        verbose_name_plural = _('Nivel Consejos Comunales')

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core import validators
from base.fields import IdentificationCardField, PhoneField
from .models import NationalLevel, StateLevel, MunicipalLevel, ParishLevel, CommunalCouncilLevel
from base.models import State, Municipality, Parish, CommunalCouncil

class ProfileForm(forms.ModelForm):
    """!
    Clase que contiene los campos del formulario de perfil del usuario

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    ## Username para identificar al usuario, en este caso se usa la cédula
    username = IdentificationCardField(
        validators=[
            validators.RegexValidator(
                r'^[VE][\d]{8}$',
                _("Introduzca un número de cédula válido. Solo se permiten números y una longitud de 8 carácteres. Se agregan ceros (0) si la longitud es de 7 o menos caracteres.")
            ),
        ],
    )

    ## Nombres del usuario
    first_name = forms.CharField(
        label=_("Nombres:"), max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique los Nombres"),
            }
        )
    )

    ## Apellidos del usuario
    last_name = forms.CharField(
        label=_("Apellidos:"), max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique los Apellidos"),
            }
        )
    )

    ## Correo del usuario
    email = forms.EmailField(
        label=_("Correo Electrónico:"), max_length=100,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control input-sm email-mask', 'data-toggle': 'tooltip',
                'title': _("Indique el correo electrónico de contacto")
            }
        )
    )

    ## Teléfono del usuario
    phone = PhoneField(
        validators=[
            validators.RegexValidator(
                r'^\+\d{2}-\d{3}-\d{7}$',
                _("Número telefónico inválido. Solo se permiten números y los símbolos: + -")
            ),
        ],
    )

    ## Clave de acceso del usuario
    password = forms.CharField(
        label=_("Contraseña:"), max_length=128,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique una contraseña de aceso al sistema")
            }
        )
    )

    ## Confirmación de clave de acceso del usuario
    confirm_password = forms.CharField(
        label=_("Verificar Contraseña:"), max_length=128,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique nuevamente la contraseña de aceso al sistema")
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError(_("El correo ya esta registrado"))
        return email

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        password = self.data['password']
        if password != confirm_password:
            raise forms.ValidationError(_("La contraseña no es la misma"))

        return confirm_password

    class Meta:
        """!
        Meta clase del formulario que establece algunas propiedades

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        model = User
        exclude = ['profile','level','date_joined']

class NationalLevelUpdateForm(ProfileForm):
    """!
    Clase que contiene el formulario para poder actualizar los datos de un usuario que tiene nivel Nacional

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 04-03-2018
    @version 1.0.0
    """

    def __init__(self, *args, **kwargs):
        """!
        Función que inicializa el formulario

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 04-03-2018
        @version 1.0.0
        """

        super(NationalLevelUpdateForm, self).__init__(*args, **kwargs)
        self.fields['country'].required = False
        self.fields['password'].required = False
        self.fields['confirm_password'].required = False
        self.fields['password'].widget.attrs['disabled'] = True
        self.fields['confirm_password'].widget.attrs['disabled'] = True

    ## Estado donde se encuentra el usuario
    country = forms.CharField(
        label=_("País:"),
        widget=forms.TextInput(attrs={
            'class': 'form-control input-sm', 'data-toggle': 'tooltip', 'readonly':'true',
            'title': _("Indica el nombre del pais"),
        })
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exclude(username=username):
            raise forms.ValidationError(_("El correo ya esta registrado"))
        return email

    def clean_confirm_password(self):
        pass

    class Meta:
        """!
        Meta clase del formulario que establece algunas propiedades

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        model = User
        exclude = [
            'profile','level','password','confirm_password','date_joined','last_login','is_active',
            'is_superuser','is_staff', 'pcountry'
        ]

class StateLevelForm(ProfileForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(StateLevelForm, self).__init__(*args, **kwargs)
        national_level = NationalLevel.objects.get(profile=user.profile)
        list_state = [('','Selecione...')]
        for st in State.objects.filter(country=national_level.country):
            list_state.append( (st.id,st) )
        self.fields['state'].choices = list_state

    state = forms.ChoiceField(
        label=_('Estado:'),
        widget=forms.Select(attrs={
            'class': 'form-control select2', 'data-toggle': 'tooltip',
            'title': _("Seleccione el estado"),
        })
    )

    def clean_state(self):
        state = self.cleaned_data['state']

        if StateLevel.objects.filter(state=state):
            raise forms.ValidationError(_("Ya existe un usuario asignado a este estado"))

        return state

class StateLevelUpdateForm(ProfileForm):
    """!
    Clase que contiene el formulario para poder actualizar los datos de un usuario que tiene nivel estadal

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    def __init__(self, *args, **kwargs):
        """!
        Función que inicializa el formulario

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        super(StateLevelUpdateForm, self).__init__(*args, **kwargs)
        self.fields['state'].required = False
        self.fields['password'].required = False
        self.fields['confirm_password'].required = False
        self.fields['password'].widget.attrs['disabled'] = True
        self.fields['confirm_password'].widget.attrs['disabled'] = True

    ## Estado donde se encuentra el usuario
    state = forms.CharField(
        label=_("Estado:"),
        widget=forms.TextInput(attrs={
            'class': 'form-control input-sm', 'data-toggle': 'tooltip', 'readonly': 'true',
            'title': _("Indica el nombre del estado"),
        })
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exclude(username=username):
            raise forms.ValidationError(_("El correo ya esta registrado"))
        return email

    def clean_confirm_password(self):
        pass

    class Meta:
        """!
        Meta clase del formulario que establece algunas propiedades

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        model = User
        exclude = [
            'profile','level','password','confirm_password','date_joined','last_login','is_active',
            'is_superuser','is_staff','state'
        ]

class MunicipalLevelForm(ProfileForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(MunicipalLevelForm, self).__init__(*args, **kwargs)
        state_level = StateLevel.objects.get(profile=user.profile)
        list_municipality = [('','Selecione...')]
        for mu in Municipality.objects.filter(state=state_level.state):
            list_municipality.append( (mu.id,mu) )
        self.fields['municipality'].choices = list_municipality

    municipality = forms.ChoiceField(
        label=_("Municipio:"),

user/templates/user/municipal.level.create.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">{% trans 'Registrar - Municipal' %}</h4>
        </div>
        <div class="panel-body">
	        <form action="" role="form" class="form form-horizontal validate-form" method="post" autocomplete="off">
                {% csrf_token %}

                {% include 'user/profile.create.html' %}

                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group {% if form.municipality.errors %}has-error{% endif %}">
                            <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.municipality.auto_id }}">
                                {{ form.municipality.label }}
                            </label>
                            <div class="col-md-9 col-xs-9 col-sm-9">
                                <div class="form-inline">
                                    {{ form.municipality }}
                                    <i class="ion ion-ios-medical item-requerido"></i>
                                </div>
                                {% include 'base/form.errors.html' with form_errors=form.municipality.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <a href="{% url 'user:municipal_level_list' %}" class="btn btn-primary btn-sm">{% trans 'Atrás' %}</a>
                    <button type="reset" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Limpiar' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Registrar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/municipal.level.list.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">Listar - Municipal <a href="{% url 'user:municipal_level_create' %}" class="btn btn-success btn-sm pull-right">Registrar</a></h4>
        </div>

        <div class="panel-body">
            <div class="row table-responsive">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <table class="table table-striped table-hover table-bordered display dataTable" id="table">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Correo</th>
                                <th>Teléfono</th>
                                <th>Municipio</th>
                                <th>Estado</th>
                                <th>País</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for mun in object_list %}
                                <tr>
                                <td> {{ mun.profile.user.username }} </td>
                                <td> {{ mun.profile.user.first_name }} </td>
                                <td> {{ mun.profile.user.last_name }} </td>
                                <td> {{ mun.profile.user.email }} </td>
                                <td> {{ mun.profile.phone }} </td>
                                <td> {{ mun.municipality }} </td>
                                <td> {{ mun.municipality.state }} </td>
                                <td> {{ mun.municipality.state.country }} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_footer %}
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "order": [[ 6, "asc" ],[ 5, "asc" ]]
            });

            button_datatable(table);
        });
    </script>
{% endblock %}

user/templates/user/parish.level.create.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">{% trans 'Registrar - Parroquial' %}</h4>
        </div>
        <div class="panel-body">
	        <form action="" role="form" class="form form-horizontal validate-form" method="post" autocomplete="off">
                {% csrf_token %}

                {% include 'user/profile.create.html' %}

                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group {% if form.parish.errors %}has-error{% endif %}">
                            <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.parish.auto_id }}">
                                {{ form.parish.label }}
                            </label>
                            <div class="col-md-9 col-xs-9 col-sm-9">
                                <div class="form-inline">
                                    {{ form.parish }}
                                    <i class="ion ion-ios-medical item-requerido"></i>
                                </div>
                                {% include 'base/form.errors.html' with form_errors=form.parish.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <a href="{% url 'user:parish_level_list' %}" class="btn btn-primary btn-sm">{% trans 'Atrás' %}</a>
                    <button type="reset" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Limpiar' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Registrar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/parish.level.list.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">Listar - Parroquial <a href="{% url 'user:parish_level_create' %}" class="btn btn-success btn-sm pull-right">Registrar</a></h4>
        </div>

        <div class="panel-body">
            <div class="row table-responsive">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <table class="table table-striped table-hover table-bordered display dataTable" id="table">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Correo</th>
                                <th>Teléfono</th>
                                <th>Parroquia</th>
                                <th>Municipio</th>
                                <th>Estado</th>
                                <th>País</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for par in object_list %}
                                <tr>
                                <td> {{ par.profile.user.username }} </td>
                                <td> {{ par.profile.user.first_name }} </td>
                                <td> {{ par.profile.user.last_name }} </td>
                                <td> {{ par.profile.user.email }} </td>
                                <td> {{ par.profile.phone }} </td>
                                <td> {{ par.parish }} </td>
                                <td> {{ par.parish.municipality }} </td>
                                <td> {{ par.parish.municipality.state }} </td>
                                <td> {{ par.parish.municipality.state.country }} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_footer %}
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "order": [[ 7, "asc" ],[ 6, "asc" ],[ 5, "asc" ]]
            });

            button_datatable(table);
        });
    </script>
{% endblock %}

user/templates/user/password_reset_form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}Usuario{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">Recuperar Contraseña</h3>
        </div>
        <div class="panel-body">
            <form method="post">
	            {% csrf_token %}
	            <label for="id_email">Correo:</label> {{ form.email }}
                <div class="text-right">
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Enviar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/state.level.create.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">{% trans 'Registrar - Estadal' %}</h4>
        </div>
        <div class="panel-body">
	        <form action="" role="form" class="form form-horizontal validate-form" method="post" autocomplete="off">
                {% csrf_token %}

                {% include 'user/profile.create.html' %}

                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group {% if form.state.errors %}has-error{% endif %}">
                            <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.state.auto_id }}">
                                {{ form.state.label }}
                            </label>
                            <div class="col-md-9 col-xs-9 col-sm-9">
                                <div class="form-inline">
                                    {{ form.state }}
                                    <i class="ion ion-ios-medical item-requerido"></i>
                                </div>
                                {% include 'base/form.errors.html' with form_errors=form.state.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <a href="{% url 'user:state_level_list' %}" class="btn btn-primary btn-sm">{% trans 'Atrás' %}</a>
                    <button type="reset" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Limpiar' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Registrar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/user/state.level.list.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">Listar - Estadal <a href="{% url 'user:state_level_create' %}" class="btn btn-success btn-sm pull-right">Registrar</a></h4>
        </div>

        <div class="panel-body">
            <div class="row table-responsive">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <table class="table table-striped table-hover table-bordered display dataTable" id="table">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Correo</th>
                                <th>Teléfono</th>
                                <th>Estado</th>
                                <th>País</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for st in object_list %}
                                <tr>
                                <td> {{ st.profile.user.username }} </td>
                                <td> {{ st.profile.user.first_name }} </td>
                                <td> {{ st.profile.user.last_name }} </td>
                                <td> {{ st.profile.user.email }} </td>
                                <td> {{ st.profile.phone }} </td>
                                <td> {{ st.state }}</td>
                                <td> {{ st.state.country }} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_footer %}
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "order": [[ 5, "asc" ]]
            });

            button_datatable(table);
        });
    </script>
{% endblock %}