base/urls.py
from django.urls import path, re_path
from .views import HomeView, Error403View
from .ajax import ComboUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'base'

## urls de la aplicación base
urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('error-403/', Error403View.as_view(), name = "error_403"),
]

urlpatterns += [
    re_path(r'^ajax/actualizar-combo/?$', login_required(ComboUpdateView.as_view()), name='combo_update'),
]

user/urls.py
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from .views import (
    NationalLevelUpdateView, StateLevelListView, StateLevelCreateView, StateLevelUpdateView, MunicipalLevelListView,
    MunicipalLevelCreateView, ParishLevelListView, ParishLevelCreateView, MunicipalLevelUpdateView, ParishLevelUpdateView,
    CommunalCouncilLevelListView, CommunalCouncilLevelCreateView, CommunalCouncilLevelUpdateView
)
from django.urls import reverse_lazy

app_name = 'user'

urlpatterns = [
    path('login/', views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),

    path('reset/password_reset/', views.PasswordResetView.as_view(template_name='user/password_reset_form.html',
        email_template_name='user/password_reset_email.html',success_url=reverse_lazy('user:password_reset_done')),
        name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/',views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
        name='password_reset_complete'),

    path('cambiar-clave/', login_required(views.PasswordChangeView.as_view(template_name='user/password_change_form.html')),
        name='password_change'),
    path('cambiar-clave-hecho/', login_required(views.PasswordChangeDoneView.as_view(template_name='user/password_change_done.html')),
        name='password_change_done'),

    path('nacional/actualizar/<int:pk>/', login_required(NationalLevelUpdateView.as_view()), name='national_level_update'),
    path('estadal/', login_required(StateLevelListView.as_view()), name='state_level_list'),
    path('estadal/registrar/', login_required(StateLevelCreateView.as_view()), name='state_level_create'),

    path('estadal/actualizar/<int:pk>/', login_required(StateLevelUpdateView.as_view()), name='state_level_update'),
    path('municipal/', login_required(MunicipalLevelListView.as_view()), name='municipal_level_list'),
    path('municipal/registrar/', login_required(MunicipalLevelCreateView.as_view()), name='municipal_level_create'),

    path('municipal/actualizar/<int:pk>/', login_required(MunicipalLevelUpdateView.as_view()), name='municipal_level_update'),
    path('parroquial/', login_required(ParishLevelListView.as_view()), name='parish_level_list'),
    path('parroquial/registrar/', login_required(ParishLevelCreateView.as_view()), name='parish_level_create'),

    path('parroquial/actualizar/<int:pk>/', login_required(ParishLevelUpdateView.as_view()), name='parish_level_update'),
    path('comunal/', login_required(CommunalCouncilLevelListView.as_view()), name='communal_council_level_list'),
    path('comunal/registrar/', login_required(CommunalCouncilLevelCreateView.as_view()), name='communal_council_level_create'),

    path('comunal/actualizar/<int:pk>/', login_required(CommunalCouncilLevelUpdateView.as_view()), name='communal_council_level_update'),
]

base/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Country(models.Model):
    """!
    Clase que contiene los paises

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    ## Nombre del pais
    name = models.CharField(max_length=80)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        return self.name

class State(models.Model):
    """!
    Clase que contiene los estados que se encuentran en un país

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    ## Nombre del Estado
    name = models.CharField(max_length=50)

    ## Pais en donde esta ubicado el Estado
    country = models.ForeignKey(Country,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        return self.name

class Municipality(models.Model):
    """!
    Clase que contiene los municipios que se encuentran en un estado

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    ## Nombre del Municipio
    name = models.CharField(max_length=50)

    ## Estado en donde se encuentra el Municipio
    state = models.ForeignKey(State,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        return self.name

class City(models.Model):
    """!
    Clase que contiene las ciudades que se encuentran en un estado

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    ## Nombre de la Ciudad
    name = models.CharField(max_length=50)

    ## Estado en donde se encuentra ubicada la Ciudad
    state = models.ForeignKey(State,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        return self.name

class Parish(models.Model):
    """!
    Clase que contiene las parroquias que se encuentran un municipio

    @author Ing. Roldan Vargas (rvargas at cenditel.gob.ve)
    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    ## Nombre de la Parroquia
    name = models.CharField(max_length=50)

    ## Municipio en el que se encuentra ubicada la Parroquia
    municipality = models.ForeignKey(Municipality,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Función para representar la clase de forma amigable

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
        @date 14-01-2018
        @version 1.0.0
        """

        return self.name

class CommunalCouncil(models.Model):

    ## Número de rif del Consejo Comunal
    rif = models.CharField(
        max_length=10, primary_key=True
    )

    ## Nombre del Consejo Comunal
    name = models.CharField(max_length=500, verbose_name='Nombre')

    ## Parroquia en el que se encuetra ubicado el Consejo Comunal
    parish = models.ForeignKey(Parish,on_delete=models.CASCADE, verbose_name='Parroquia')

    def __str__(self):
        return self.rif + ' | ' + self.name

    class Meta:
        verbose_name = _("Consejo Comunal")
        verbose_name_plural = _("Consejos Comunales")

base/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import State, Municipality, Parish, CommunalCouncil
from .fields import RifField

class CommunalCouncilAdminForm(forms.ModelForm):

    ## Rif del consejo comunal
    rif = RifField()

    ## Nombre del consejo comunal
    name = forms.CharField(
        label=_("Nombre del Consejo Comunal:"),
        max_length=500,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique el Nombre del RIF"),
            }
        )
    )

    ## Estado donde se ecnuetra ubicado el municipio
    state = forms.ModelChoiceField(
        label=_("Estado:"), queryset=State.objects.all(), empty_label=_("Seleccione..."),
        widget=forms.Select(attrs={
            'class': 'form-control select2', 'data-toggle': 'tooltip',
            'title': _("Seleccione el estado en donde se encuentra ubicada"),
        })
    )

    ## Municipio donde se encuentra ubicada la parroquia
    municipality = forms.ModelChoiceField(
        label=_("Municipio:"), queryset=Municipality.objects.all(), empty_label=_("Seleccione..."),
        widget=forms.Select(attrs={
            'class': 'form-control select2', 'data-toggle': 'tooltip', 'disabled': 'true',
            'title': _("Seleccione el municipio en donde se encuentra ubicada"),
        })
    )

    ## Parroquia donde se encuentra ubicado el consejo comunal
    parish = forms.ModelChoiceField(
        label=_("Parroquia:"), queryset=Parish.objects.all(), empty_label=_("Seleccione..."),
        widget=forms.Select(attrs={
            'class': 'form-control select2', 'data-toggle': 'tooltip', 'disabled': 'true',
            'title': _("Seleccione la parroquia en donde se encuentra ubicada"),
        })
    )

    class Meta:

        model = CommunalCouncil
        fields = [
            'rif','name','state','municipality','parish'
        ]

base/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from user.models import NationalLevel, StateLevel, MunicipalLevel, ParishLevel, CommunalCouncilLevel

class HomeView(TemplateView):
    """!
    Clase para mostrar la página de inicio según el nivel de usuario

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 26-01-2018
    @version 1.0.0
    """

    template_name = "base/base.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        profile = self.request.user.profile
        if profile.level == 0:
            context['texto1'] = 'Bienvenido ' + str(profile)
            context['texto2'] = 'Usuario nivel administrador. Este usuario permite registrar y eliminar \
            a cualquier usuario desde el panel administrativo'
        elif profile.level == 1:
            national_level = NationalLevel.objects.get(profile=profile)
            context['texto1'] = 'Bienvenido ' + str(profile)
            context['texto2'] = 'Usuario nivel nacional ' + str(national_level.country) + '. Este usuario permite registrar y monitoriar a los representantes de \
            cada estado que pertenecen a dicho país'
        elif profile.level == 2:
            state_level = StateLevel.objects.get(profile=profile)
            context['texto1'] = 'Bienvenido ' + str(profile)
            context['texto2'] = 'Usuario nivel estado ' + str(state_level.state) + '. Este usuario permite registrar y monitoriar a los representantes de \
            cada municipio que pertenecen a dicho estado'
        elif profile.level == 3:
            municipal_level = MunicipalLevel.objects.get(profile=profile)
            context['texto1'] = 'Bienvenido ' + str(profile)
            context['texto2'] = 'Usuario nivel municipio ' + str(municipal_level.municipality) + '. Este usuario permite registrar y monitoriar a los representantes \
            de cada parroquia que pertenecen a dicho municipio'
        elif profile.level == 4:
            parish_level = ParishLevel.objects.get(profile=profile)
            context['texto1'] = 'Bienvenido ' + str(profile)
            context['texto2'] = 'Usuario nivel parroquia ' + str(parish_level.parish) + '. Este usuario permite registrar y monitoriar a los representantes \
            de cada consejo comunal que pertenecen a dicha parroquia'
        elif profile.level == 5:
            communal_council_level = CommunalCouncilLevel.objects.get(profile=profile)
            context['texto1'] = 'Bienvenido ' + str(profile)
            context['texto2'] = 'Usuario nivel consejo comunal ' + str(communal_council_level.communal_council) + '. Este usuario permite registrar, actualizar, eliminar y listar \
            a todos los adultos mayores'
        return context

class Error403View(TemplateView):
    """!
    Clase para mostrar error de permiso

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-3.0.html'>GNU Public License versión 3 (GPLv3)</a>
    @date 14-01-2018
    @version 1.0.0
    """

    template_name = "base/error.403.html"

base/templates/base/base.html
<!DOCTYPE html>
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"es-ve" }}">
    {% include 'base/head.html' %}
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'base:home' %}">Adulto Mayor</a>
                </div>
                {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Menú<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if request.user.profile.level == 1 %}
                            <li><a href="{% url 'user:state_level_list' %}">Estadal</a></li>
                            <li><a href="{% url 'user:municipal_level_list' %}">Municipal</a></li>
                            <li><a href="{% url 'user:parish_level_list' %}">Parroquial</a></li>
                            <li><a href="{% url 'user:communal_council_level_list' %}">Consejo Comunal</a></li>
                            {% elif request.user.profile.level == 2 %}
                            <li><a href="{% url 'user:municipal_level_list' %}">Municipal</a></li>
                            <li><a href="{% url 'user:parish_level_list' %}">Parroquial</a></li>
                            <li><a href="{% url 'user:communal_council_level_list' %}">Consejo Comunal</a></li>
                            {% elif request.user.profile.level == 3 %}
                            <li><a href="{% url 'user:parish_level_list' %}">Parroquial</a></li>
                            <li><a href="{% url 'user:communal_council_level_list' %}">Consejo Comunal</a></li>
                            {% elif request.user.profile.level == 4 %}
                            <li><a href="{% url 'user:communal_council_level_list' %}">Consejo Comunal</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-user fa-lg" aria-hidden="true"></i> {{ request.user.username }}</a>
                    <ul class="dropdown-menu">
                        {% if request.user.profile.level == 1 %}
                        <li><a href="{% url 'user:national_level_update' request.user.id %}"> Perfil</a></li>
                        {% elif request.user.profile.level == 2 %}
                        <li><a href="{% url 'user:state_level_update' request.user.id %}"> Perfil</a></li>
                        {% elif request.user.profile.level == 3 %}
                        <li><a href="{% url 'user:municipal_level_update' request.user.id %}"> Perfil</a></li>
                        {% elif request.user.profile.level == 4 %}
                        <li><a href="{% url 'user:parish_level_update' request.user.id %}"> Perfil</a></li>
                        {% elif request.user.profile.level == 5 %}
                        <li><a href="{% url 'user:communal_council_level_update' request.user.id %}"> Perfil</a></li>
                        {% endif %}
                        <li><a href="{% url 'user:password_change' %}"> Cambiar Clave</a></li>
                        <li><a href="{% url 'user:logout' %}"><i class="fa fa-sign-out fa-lg" aria-hidden="true"></i> Salir</a></li>
                    </ul>
                </ul>
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'user:login' %}"><i class="fa fa-sign-in fa-lg" aria-hidden="true"></i> Iniciar Sesión</a></li>
                </ul>
                {% endif %}
            </div>
        </nav>

        <div class="container-fluid">
            <h2>{% block content_header_title %}{% trans 'Página Principal' %}{% endblock %}</h2>
            {% block contenido %}
                {% if request.user.is_authenticated %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="text-center">{{ texto1 }}</h4>
                        </div>
                        <div class="panel-body">
                            <h4 class="text-center">{{ texto2 }}</h4>
                        </div>
                    </div>
                {% endif %}
            {% endblock %}
        </div>
        {% include 'base/footer.html' %}
        {% block extra_footer %}

        {% endblock %}
    </body>
</html>

base/templates/base/error.403.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}<br>{% endblock %}
{% block contenido %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="text-left">Error</h4>
        </div>
        <div class="panel-body">
            <h3 class="text-center"><i class="fa fa-warning text-red"></i> Oops! No tiene permiso de acceso a esta página.</h3>
            <p class="text-center">
                No puedes acceder a la pagina que buscas.
                Puedes <b><a href="{% url 'base:home' %}">retornar a inicio</a></b> o solicitar al administrador permisos de acceso.
            </p>
        </div>
    </div>
{% endblock %}

base/templates/base/footer.html
{% load static from staticfiles %}
{% load i18n %}
<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}" type="text/javascript"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
<!-- Select2 -->
<script src="{% static 'node_modules/select2/dist/js/select2.full.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/jquery-mask-plugin/dist/jquery.mask.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/functions.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net/js/jquery.dataTables.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/dataTables.buttons.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-bs/js/dataTables.bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/buttons.html5.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/buttons.flash.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/datatables.net-buttons/js/buttons.print.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/jszip/dist/jszip.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/pdfmake/build/pdfmake.min.js' %}" type="text/javascript"></script>
<script src="{% static 'node_modules/pdfmake/build/vfs_fonts.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function(){
        //muestra los mensajes centrados
        $('[data-toggle="tooltip"]').tooltip();

        //para agregar el select2 en los respectivos campos de tipo select
        $(".select2").select2();
    });

    $.extend( true, $.fn.dataTable.defaults, {
        "language": {
            "sProcessing":     "Procesando...",
            "sLengthMenu":     "Mostrar _MENU_ registros",
            "sZeroRecords":    "No se encontraron resultados",
            "sEmptyTable":     "Ningún dato disponible en esta tabla",
            "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
            "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix":    "",
            "sSearch":         "Buscar:",
            "sUrl":            "",
            "sInfoThousands":  ",",
            "sLoadingRecords": "Cargando...",
            "oPaginate": {
                "sFirst":    "Primero",
                "sLast":     "Último",
                "sNext":     "Siguiente",
                "sPrevious": "Anterior"
            },
            "oAria": {
                "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            },
        },
    });
</script>

base/templates/base/form.errors.html
{% load i18n %}
{% if form_errors %}
    <div class="error-notice">
        <div class="oaerror danger">
            <div class="row">
                <div class="{% if not col_title_error %}col-sm-3{% else %}{{ col_title_error }}{% endif %}">
                    <strong>{% trans 'Error' %}</strong>
                </div>
                <div class="{% if not col_msg_error %}col-sm-9{% else %}{{ col_msg_error }}{% endif %}">
                    {% if custom_message_error %}{{ custom_message_error }}{% else %}{{ form_errors }}{% endif %}
                </div>
            </div>
        </div>
    </div>
{% endif %}

base/templates/base/head.html
{% load static from staticfiles %}
{% load i18n %}
<head>
	<meta charset="UTF-8">
	<title>{% trans 'Adulto Mayor' %}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
    <meta name="description" content="{% trans 'Registro de los adultos mayores' %}">
    <meta name="author" content="William Páez (wpaez at cenditel.gob.ve)">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/select2/dist/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/ionicons/dist/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'node_modules/datatables.net-bs/css/dataTables.bootstrap.css' %}">
    {% block extra_head %}

    {% endblock %}
</head>